spring:
  application:
    name: pokemon-tcg-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/pokemontcg?TimeZone=UTC
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
    show-sql: false

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

server:
  port: ${PORT:8080}

pokemontcg:
  base-url: https://api.pokemontcg.io/v2
  api-key: ${POKEMON_TCG_API_KEY:}

management:
  endpoints:
    web:
      exposure:
        include: health,info
