CREATE TABLE realtime_events (
    sequence BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schema_version INTEGER NOT NULL,
    game_id UUID NOT NULL,
    type VARCHAR(64) NOT NULL,
    payload_json TEXT NOT NULL,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    received_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_realtime_events_game_sequence
    ON realtime_events (game_id, sequence);

