server:
  port: ${PORT:8083}

spring:
  application:
    name: card-service
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6380}

pokemontcg:
  base-url: https://api.pokemontcg.io/v2
  api-key: ${POKEMON_TCG_API_KEY:}
